spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/greengram
    username: root
    password: green502

mybatis:
  mapper-locations: abc/*.xml


springdoc:
  swagger-ui:
    path: /swagger.html



server:
  port: 8081